language: node_js
node_js:
  - '0.12'
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g bower grunt-cli
  - gem install sass
  - bower install
services: mongodb
script:
  - USE_SAUCELABS=0 grunt test
#   - grunt test:e2e:prod
# addons:
#   sauce_connect: true
# env:
#   global:
#     - PROTRACTOR_BROWSERS=firefox
#     - KARMA_BROWSERS=Firefox,PhantomJS
#     - KARMA_REPORTERS=spec
#     # SAUCELABS
#     - secure: "HOSLV7FkU4t5TpOoDU1Sb3ctfjOiIjHkiO+1epGtioh5XzyGDDh8cwvHZAk+JzFUxvis2mhQsaxttyjEIAFFWLtxwctpz5hAP2knHThCzbsMWwf91Y8dBXJc03T6YJ0/9MrUAn3yMHMYzxS3qF8hwVXUikVhsT3HD7lYZk7uYw8CQz1b6MFEISTtwLvxVsN6wwkXl8zRWSHtP6c+b+jdqtLhcDl48+qv+s4nhUNKjuJcBAbV/RmJ8oOhGnNBTqTVvJl6kxzYv7d9m5Gh6p6pGmTDbGW5MupoShVy7vQPmcA4wamOFmmk8eY1nFp3pZ92kXwupuiS0CLzf9iSCmgWguwWy7MwtggGXXpb4ozBs3muwy0uGTAurY2pdVvi60tqhJdRz80hUujNdGqhzuvD9RVEjkp3BbE8FoA1fizVTZn7rCgHUhHwAbCmKuk+OhRfoPcsob5fndefSnNyg/Ys3/xyB9oftt+IMITez8BYxl3IjJ9XGGNXbz/ZKOoMOcBKcOzfdy6lQthKzu47OjYwNqrwTNSsf0gRxi6t9zJyeNBFOtQ0hRbAkcnOxjy+d1phdShLGGZIAOHVj7siwS8ab6f4I4ntSjv7hR3D+95SOHkVmah2QzP3w5O91fUCIMzuIDSFJcnKOqR0tBVdRxj8NVUn7qgFckPiawlqsMWnGEA="
#     - secure: "J8Y/K/ypnISaAtl0J8FcNVwIsWAmMQOdLP8qOM+beT3ZI3hu2uPfZCrCTU52HdGh2IAnDT2E/38rMFQG9cvyiOkkETOSuIXMweemGWRdalGRP2B+qwjKnTIj8miPVnh8KmpzOtrEKjMC+TTHCQ4sDQKrz16RkvPNiiQ/hq/9Uaz0ubKhmyKqpY6HWbbffn3pT755l4cACyOW9K5T5jQt+7icTX3Puk3O9YKHwRQWb0vUSwEb1SAGNT6jL91Oh0iHA4snFgkc2w2cpqi1+c/HhlaJaRlzHESEAzNyQxwbg7hlxIKbciUscDfOTJPacbiiaQcCKHL4Uzcke1a9fULSGlsaA1Dz40r9O/qIUrO38CLcdZ7Qg2JDVcYETm4h0M5pJChDEgkeR3NEujSIogOpNJP3nJh8NyrxY2EO5mZ574z3HREDTcU8/+Z3QTebgf4r3Hivl1CNoZC0OZW4RGZgMqizZw20W/6Kuoa5HbShcCVjByu486rm+uo6QMT9l1mFAq+WFla5tRnB9rZMs3Nx6bR3eSn54kUfIEtdkA5GnKP7pcICZfthnDVh+AdJCKXrAUDPaHZHEw2EWJvGpcr48wvmIkhVn4LaqKzHe2Je7Yih9Eu5Gnbu+MkPiv3woqwBf0x3Nc4B30MfUOtmJV46NSxgASi7aX3TzvPP6HzGARc="
#
#  ==== alternatives ====
#
# - https://github.com/shippableSamples/sample_node_protractor/blob/master/shippable.yml
# - https://docs.snap-ci.com/the-ci-environment/testing-with-browsers/
